# Generated by Django 6.0.4 on 2026-04-28 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='books_book_slug_ca552e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_active', '-created_at'], name='books_book_is_acti_9db341_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category', 'is_active'], name='books_book_categor_9bc7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['grade_level', 'is_active'], name='books_book_grade_l_5f7cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrequest',
            index=models.Index(fields=['status', '-created_at'], name='books_bookr_status_5afa5e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrequest',
            index=models.Index(fields=['user', '-created_at'], name='books_bookr_user_id_9e3a14_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrequest',
            index=models.Index(fields=['priority'], name='books_bookr_priorit_3252b4_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', '-created_at'], name='books_bookr_book_id_4a01df_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['user', '-created_at'], name='books_bookr_user_id_87ebf2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['is_approved'], name='books_bookr_is_appr_4ece1b_idx'),
        ),
        migrations.AddIndex(
            model_name='contributorapplication',
            index=models.Index(fields=['status'], name='books_contr_status_8c02d1_idx'),
        ),
        migrations.AddIndex(
            model_name='contributorapplication',
            index=models.Index(fields=['user', '-created_at'], name='books_contr_user_id_97c7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='contributorearning',
            index=models.Index(fields=['contributor', '-created_at'], name='books_contr_contrib_935efd_idx'),
        ),
        migrations.AddIndex(
            model_name='contributorearning',
            index=models.Index(fields=['book'], name='books_contr_book_id_cf8716_idx'),
        ),
        migrations.AddIndex(
            model_name='contributorwithdrawal',
            index=models.Index(fields=['status'], name='books_contr_status_39113c_idx'),
        ),
        migrations.AddIndex(
            model_name='contributorwithdrawal',
            index=models.Index(fields=['contributor', '-created_at'], name='books_contr_contrib_25308f_idx'),
        ),
    ]
