# Generated by Django 6.0.4 on 2026-04-29 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_books_book_slug_ca552e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='The contributor who uploaded this book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.contributor'),
        ),
        migrations.AddField(
            model_name='book',
            name='earnings_paid',
            field=models.BooleanField(default=False, help_text='Whether contributor has been paid for this book'),
        ),
        migrations.AddField(
            model_name='book',
            name='earnings_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['contributor'], name='books_book_contrib_1cbe09_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['contributor', '-created_at'], name='books_book_contrib_58e1df_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_active', 'is_free'], name='books_book_is_acti_a534b0_idx'),
        ),
    ]
