# Generated by Django 6.0.4 on 2026-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_book_contributor_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookreview',
            name='books_bookr_book_id_4a01df_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookreview',
            name='books_bookr_user_id_87ebf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookreview',
            name='books_bookr_is_appr_4ece1b_idx',
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')]),
        ),
    ]
