# Generated by Django 6.0.4 on 2026-04-29 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_bookreview_books_bookr_book_id_4a01df_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐ 1 Star - Poor'), (2, '⭐⭐ 2 Stars - Fair'), (3, '⭐⭐⭐ 3 Stars - Good'), (4, '⭐⭐⭐⭐ 4 Stars - Very Good'), (5, '⭐⭐⭐⭐⭐ 5 Stars - Excellent')]),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', '-created_at'], name='books_bookr_book_id_4a01df_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['user', '-created_at'], name='books_bookr_user_id_87ebf2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['is_approved'], name='books_bookr_is_appr_4ece1b_idx'),
        ),
    ]
