# Generated by Django 6.0.4 on 2026-05-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_bookreview_rating_and_more'),
    ]

    operations = [
    ]
