# Generated by Django 6.0.4 on 2026-05-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_increase_category_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='book', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
