# Generated by Django 6.0.4 on 2026-04-28 22:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('guest', 'Guest Account'), ('basic', 'Basic - Free Plan'), ('premium', 'Premium - Monthly Subscription'), ('lifetime', 'Lifetime - One-time Payment'), ('institution', 'Institutional License')], default='basic', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +260XXXXXXXXX or 09XXXXXXXX', regex='^\\+?260?\\d{9}$')])),
                ('national_id', models.CharField(blank=True, help_text='Zambian National Registration Card (NRC) number', max_length=20, null=True, unique=True)),
                ('province', models.CharField(blank=True, choices=[('central', 'Central Province'), ('copperbelt', 'Copperbelt Province'), ('eastern', 'Eastern Province'), ('luapula', 'Luapula Province'), ('lusaka', 'Lusaka Province'), ('muchinga', 'Muchinga Province'), ('northern', 'Northern Province'), ('northwestern', 'North-Western Province'), ('southern', 'Southern Province'), ('western', 'Western Province')], max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('constituency', models.CharField(blank=True, max_length=100)),
                ('school_or_work', models.CharField(blank=True, max_length=200)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('credits_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance in Zambian Kwacha (K)', max_digits=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('total_downloads', models.IntegerField(default=0)),
                ('total_uploads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BiometricCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
