# Generated by Django 6.0.4 on 2026-04-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_biometricdevice_loginhistory_twofactorauth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriccredential',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometriccredential',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address at registration time', null=True),
        ),
        migrations.AddField(
            model_name='biometriccredential',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this credential is active'),
        ),
        migrations.AddField(
            model_name='biometriccredential',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/device user agent'),
        ),
        migrations.AlterField(
            model_name='biometriccredential',
            name='credential_id',
            field=models.CharField(db_index=True, help_text='Unique identifier for the credential', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='biometriccredential',
            name='device_name',
            field=models.CharField(blank=True, help_text='Name of the device (e.g., iPhone 12, Laptop)', max_length=100),
        ),
        migrations.AlterField(
            model_name='biometriccredential',
            name='public_key',
            field=models.TextField(help_text='Public key for verifying signatures'),
        ),
        migrations.AlterField(
            model_name='biometriccredential',
            name='sign_count',
            field=models.IntegerField(default=0, help_text='Number of times this credential has been used'),
        ),
        migrations.AddIndex(
            model_name='biometriccredential',
            index=models.Index(fields=['user', 'is_active'], name='accounts_bi_user_id_545551_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriccredential',
            index=models.Index(fields=['credential_id'], name='accounts_bi_credent_4c9b91_idx'),
        ),
        migrations.AddIndex(
            model_name='biometriccredential',
            index=models.Index(fields=['-last_used'], name='accounts_bi_last_us_da7db1_idx'),
        ),
    ]
