# Generated by Django 6.0.4 on 2026-05-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
    ]
