# Generated by Django 6.0.4 on 2026-04-28 22:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloads_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('total_pages', models.PositiveIntegerField(default=0, help_text='Total number of pages')),
            ],
        ),
        migrations.CreateModel(
            name='BookDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the downloader')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Device information')),
                ('is_premium', models.BooleanField(default=False, help_text='Whether the downloader has premium access')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid for this download', max_digits=10)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='User session identifier', max_length=100)),
                ('referrer', models.URLField(blank=True, help_text='Referring page URL')),
                ('download_duration', models.FloatField(default=0.0, help_text='Time taken to complete download in seconds')),
                ('download_success', models.BooleanField(default=True, help_text='Whether download completed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if download failed')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Download',
                'verbose_name_plural': 'Book Downloads',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['book', '-downloaded_at'], name='downloads_b_book_id_a438b7_idx'), models.Index(fields=['user', '-downloaded_at'], name='downloads_b_user_id_a7ed0f_idx'), models.Index(fields=['downloaded_at'], name='downloads_b_downloa_911a7f_idx'), models.Index(fields=['book', 'user'], name='downloads_b_book_id_0bc623_idx'), models.Index(fields=['session_id', '-downloaded_at'], name='downloads_b_session_91720a_idx'), models.Index(fields=['download_success'], name='downloads_b_downloa_290ab4_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookReadOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the reader', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Device information')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Anonymous session identifier', max_length=100)),
                ('pages_read', models.IntegerField(default=0, help_text='Number of pages read', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_pages', models.IntegerField(default=0, help_text='Total pages in the book (synced from book.pages)')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent reading in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('completion_percentage', models.IntegerField(default=0, help_text='Percentage of book completed', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_page', models.IntegerField(default=0, help_text='Last page the user was on')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the reader completed the book')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the book was completed', null=True)),
                ('font_size', models.IntegerField(default=100, help_text='Font size percentage', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)])),
                ('reading_mode', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('sepia', 'Sepia Mode')], default='light', max_length=20)),
                ('line_height', models.FloatField(default=1.5, help_text='Line height multiplier')),
                ('total_sessions', models.IntegerField(default=1, help_text='Number of sessions for this book')),
                ('average_session_duration', models.IntegerField(default=0, help_text='Average session duration in seconds')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_reads', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Reading Session',
                'verbose_name_plural': 'Online Reading Sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['book', '-last_activity'], name='downloads_b_book_id_4d89fe_idx'), models.Index(fields=['user', '-started_at'], name='downloads_b_user_id_cd3c4e_idx'), models.Index(fields=['completed'], name='downloads_b_complet_24de68_idx'), models.Index(fields=['-last_activity'], name='downloads_b_last_ac_4c9d06_idx'), models.Index(fields=['user', 'book'], name='downloads_b_user_id_b1836e_idx'), models.Index(fields=['session_id', '-last_activity'], name='downloads_b_session_5b9b77_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BookView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the viewer')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Device information')),
                ('referrer', models.URLField(blank=True, help_text='Referring page URL')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='User session identifier', max_length=100)),
                ('view_duration', models.IntegerField(default=0, help_text='Time spent viewing in seconds')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='Browser name', max_length=50)),
                ('os', models.CharField(blank=True, help_text='Operating system', max_length=50)),
                ('is_unique_view', models.BooleanField(default=True, help_text='Whether this is a unique view')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book View',
                'verbose_name_plural': 'Book Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['book', '-viewed_at'], name='downloads_b_book_id_df8ae8_idx'), models.Index(fields=['user', '-viewed_at'], name='downloads_b_user_id_628fb3_idx'), models.Index(fields=['viewed_at'], name='downloads_b_viewed__bc7033_idx'), models.Index(fields=['session_id'], name='downloads_b_session_21eb62_idx'), models.Index(fields=['book', 'session_id'], name='downloads_b_book_id_ea4358_idx'), models.Index(fields=['-viewed_at', 'is_unique_view'], name='downloads_b_viewed__92d886_idx')],
            },
        ),
        migrations.CreateModel(
            name='DownloadAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_downloads', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('free_downloads', models.IntegerField(default=0)),
                ('paid_downloads', models.IntegerField(default=0)),
                ('premium_downloads', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_download_time', models.FloatField(default=0.0, help_text='Average download time in seconds')),
                ('failed_downloads', models.IntegerField(default=0, help_text='Number of failed downloads')),
                ('unique_books_downloaded', models.IntegerField(default=0, help_text='Number of unique books downloaded')),
                ('downloads_by_country', models.JSONField(default=dict, help_text='Downloads grouped by country')),
                ('downloads_by_device', models.JSONField(default=dict, help_text='Downloads grouped by device type')),
                ('top_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_analytics', to='books.book')),
            ],
            options={
                'verbose_name': 'Download Analytics',
                'verbose_name_plural': 'Download Analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='downloads_d_date_d76a75_idx'), models.Index(fields=['-date', '-total_downloads'], name='downloads_d_date_caca6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDownloadLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic - 20 downloads/day'), ('premium', 'Premium - Unlimited'), ('lifetime', 'Lifetime - Unlimited'), ('institution', 'Institution - 500 downloads/day')], default='basic', max_length=20)),
                ('daily_limit', models.IntegerField(default=20, help_text='Maximum downloads per day')),
                ('monthly_limit', models.IntegerField(default=500, help_text='Maximum downloads per month')),
                ('downloads_today', models.IntegerField(default=0, help_text='Downloads count for today')),
                ('downloads_this_month', models.IntegerField(default=0, help_text='Downloads count for this month')),
                ('downloads_total', models.IntegerField(default=0, help_text='Total downloads all time')),
                ('last_reset_date', models.DateField(auto_now_add=True, help_text='Last date when daily count was reset')),
                ('last_monthly_reset', models.DateField(auto_now_add=True, help_text='Last date when monthly count was reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Download Limit',
                'verbose_name_plural': 'User Download Limits',
                'indexes': [models.Index(fields=['user', '-created_at'], name='downloads_u_user_id_6c4f53_idx'), models.Index(fields=['subscription_tier'], name='downloads_u_subscri_084d74_idx')],
            },
        ),
    ]
