# Generated by Django 6.0.4 on 2026-04-28 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_books_book_slug_ca552e_idx_and_more'),
        ('downloads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('mobile_number', models.CharField(blank=True, help_text='Mobile money number', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Book',
                'verbose_name_plural': 'Saved Books',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', '-purchased_at'], name='downloads_p_user_id_7e3f79_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['book', '-purchased_at'], name='downloads_p_book_id_26d41c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='downloads_p_status_81d78b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['transaction_id'], name='downloads_p_transac_bb4bc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='savedbook',
            index=models.Index(fields=['user', '-saved_at'], name='downloads_s_user_id_62f9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='savedbook',
            index=models.Index(fields=['book', '-saved_at'], name='downloads_s_book_id_239173_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedbook',
            unique_together={('user', 'book')},
        ),
    ]
