# Generated by Django 6.0.4 on 2026-04-29 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('airtel', 'Airtel Money'), ('mtn', 'MTN Mobile Money'), ('zamtel', 'Zamtel Kwacha'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('auto', 'Auto Processed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly Premium'), ('quarterly', 'Quarterly Premium'), ('yearly', 'Yearly Premium'), ('lifetime', 'Lifetime Access'), ('book_purchase', 'Book Purchase')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='downloads_t_transac_160570_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='downloads_t_user_id_81c9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='downloads_t_status_556f0d_idx'),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
