# Generated by Django 6.0.4 on 2026-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_transaction_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdownloadlimit',
            name='daily_limit',
            field=models.IntegerField(blank=True, help_text='Maximum downloads per day (NULL = unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='userdownloadlimit',
            name='monthly_limit',
            field=models.IntegerField(blank=True, help_text='Maximum downloads per month (NULL = unlimited)', null=True),
        ),
    ]
