# Generated by Django 6.0.4 on 2026-05-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('definition', models.TextField()),
                ('part_of_speech', models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], max_length=50)),
                ('example_sentence', models.TextField(blank=True, help_text='Example sentence using the word')),
                ('synonyms', models.TextField(blank=True, help_text='Comma-separated synonyms')),
                ('antonyms', models.TextField(blank=True, help_text='Comma-separated antonyms')),
                ('pronunciation', models.CharField(blank=True, help_text='Phonetic pronunciation', max_length=100)),
                ('origin', models.CharField(blank=True, help_text='Word origin/etymology', max_length=100)),
                ('is_zambian_term', models.BooleanField(default=False, help_text='Is this a Zambian/local term?')),
                ('local_usage', models.TextField(blank=True, help_text='How this word is used in Zambia')),
                ('audio_pronunciation', models.FileField(blank=True, null=True, upload_to='dictionary/audio/')),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dictionary Word',
                'verbose_name_plural': 'Dictionary Words',
                'ordering': ['word'],
                'indexes': [models.Index(fields=['word'], name='dictionary__word_c82ae0_idx'), models.Index(fields=['is_zambian_term'], name='dictionary__is_zamb_6fdb7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looked_up_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_history', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionaryword')),
            ],
            options={
                'verbose_name': 'User Word History',
                'verbose_name_plural': 'User Word Histories',
                'ordering': ['-looked_up_at'],
            },
        ),
    ]
